### PR TITLE
APP-107124 update Go router docs

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/163)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[630e913](https://github.com/pendo-io/pendo-mobile-sdk/pull/163/commits/630e91365cc807fdf32e90a1a8cd236b6b257ce0)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[ae52fcd](https://github.com/pendo-io/pendo-mobile-sdk/pull/163/commits/ae52fcd19c3686af2437f585690fad1cebeced68)

**Review by DavidPendo — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/163)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by DavidPendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-107124](https://pendo-io.atlassian.net/browse/APP-107124): Jira Issue APP-107124: Changed to Resolved


Branch APP-107124 deleted

**Pull request merged**
