### PR TITLE
Remove Empty line from Package.swift

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/101)

### CODE REVIEW

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/101)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-94422](https://pendo-io.atlassian.net/browse/APP-94422): Invalid state 'Backlog' for merge into master

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-94422](https://pendo-io.atlassian.net/browse/APP-94422): Jira Issue APP-94422: Changed to Resolved


Branch APP-94422 deleted

**Pull request merged**
