### PR TITLE
APP-110254 3.4 update

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/186)

### CODE REVIEW

**Review by DavidPendo — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/186)* status: all files reviewed, 1 unresolved discussion (waiting on @randmaayan)

___
*[`android/pnddocs/native-android.md` line 40 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/186#-O7he40K4wIoMsBV70bT:-O7he40K4wIoMsBV70bU:b-xtk9nh) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a2f166fa9b174a073fd1ff046657c92b4b8214f7/android/pnddocs/native-android.md#L40)):*
> ```Markdown
>     ```shell
>     dependencies {
>        implementation group:'sdk.pendo.io' , name:'pendoIO', version:'3.4+', changing:true
> ```

Should we change to 3.4 also in other places of the docs... I.e Flutter, RN

**Review by shlomipendo — APPROVED** [review]

**Review by DavidPendo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/186)* status: all files reviewed, 1 unresolved discussion (waiting on @randmaayan)

**Comment by DavidPendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-110254](https://pendo-io.atlassian.net/browse/APP-110254): Jira Issue APP-110254: Changed to Resolved


Branch APP-110254_3.4_update deleted

**Pull request merged**
