### PR TITLE
APP-85670 fixed SPM url

### PR DESCRIPTION
**Pull request by orendayan**

### CODE REVIEW

**Review by MikePendo — APPROVED** [review]

**Comment by 0xkuj** [comment]
[merge]

**Review by udilevin — APPROVED** [review]

**Comment by 0xkuj** [comment]
[merge]

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-85670](https://pendo-io.atlassian.net/browse/APP-85670): Jira Issue APP-85670: Changed to Resolved


Branch APP-85670_SPM_release deleted

**Pull request merged**
