### PR TITLE
APP-108222_simplified_integration

### PR DESCRIPTION
**Pull request by MikePendo**
- **APP-108222 ios side flutter**
- **APP-108222 android part**

- - -
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)

### CODE REVIEW

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @DavidPendo, @MaximShnirman, @MikePendo, and @udilevin)

___
*[`android/pnddocs/flutter-android.md` line 122 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5Ubdq84rJ0nTjVVZrB:-O5Ubdq84rJ0nTjVVZrC:b5exlxc) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L122)):*
> ```Markdown
>     ```
> 
>      When using `GoRouter`, apply the `addPendoListenerToDelegate` to your `GoRouter` instance. <br>
> ```

Using italic or 'NOTE' isn't aligned with our existing styling. I suggest to update it as follows:

When using `GoRouter`, apply the `addPendoListenerToDelegate` to your `GoRouter` instance. <br> Do not add the listener more than once or in the build method.<br>
___
*[`android/pnddocs/flutter-android.md` line 124 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5UavXnCSuuShcyh0OC:-O5UavXnCSuuShcyh0OD:bt9l42w) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L124)):*
> ```Markdown
>      When using `GoRouter`, apply the `addPendoListenerToDelegate` to your `GoRouter` instance. <br>
>     *NOTE*: make sure to add it once (e.g adding it in the build method will be less desired)<br>
>     `GoRouter` is supported from version 13.0 <br>
> ```

Maybe this should also be mentioned (or moved) at the top of the page in the requirements section? The same applies to AutoRoute on both the Android and iOS integration pages.

So e.x. - If using GoRouter: 13.0 or higher

**Review by MaximShnirman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @DavidPendo, @MikePendo, and @udilevin)

___
*[`android/pnddocs/flutter-android.md` line 133 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5lGZ9g9k7ZU0K8WqBW:-O5lGZ9g9k7ZU0K8WqBX:b9zfyll) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L133)):*
> ```Markdown
>         @override
>         Widget build(BuildContext context) {
>             addRouterToPendoObserver(); // Add your GoRouter instance to the Pendo observer 
> ```

מwhat is addRouterToPendoObserver()??

**Review by DavidPendo — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: all files reviewed, 4 unresolved discussions (waiting on @MikePendo and @udilevin)

___
*[`android/pnddocs/flutter-android.md` line 155 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5lSu3Z2B9-D38vLakO:-O5lSu3Z2B9-D38vLakP:b-x1etwj) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L155)):*
> ```Markdown
>     }
> 
>     final AppRouter _router = AppRouter()..config().addPendoListenerToDelegate();
> ```

We can point here to have a RouterConfig variable i.e
```
final RouterConfig _routerConfig = AppRouter().config()...addPendoListenerToDelegate();
```

**Comment by MikePendo** [comment]
*[`android/pnddocs/flutter-android.md` line 122 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5Ubdq84rJ0nTjVVZrB:-O6NZxhXB0TrxnwvZG-o:bgvg8d3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L122)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Ignore the line break
</blockquote></details>

I remover the `Note`. I think the rest is ok

**Comment by MikePendo** [comment]
*[`android/pnddocs/flutter-android.md` line 124 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5UavXnCSuuShcyh0OC:-O6N_4UcEA9qGcl1SmWi:b-7v7uzm) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L124)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Maybe this should also be mentioned (or moved) at the top of the page in the requirements section? The same applies to AutoRoute on both the Android and iOS integration pages.

So e.x. - If using GoRouter: 13.0 or higher
</blockquote></details>

thi requirement is only if they use them, its not a general requirement

**Comment by MikePendo** [comment]
*[`android/pnddocs/flutter-android.md` line 124 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5UavXnCSuuShcyh0OC:-O6N_KbN0FhOugXu-Az7:b-u3lb2k) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L124)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

thi requirement is only if they use them, its not a general requirement
</blockquote></details>

you think it still should be in front ?

**Comment by MikePendo** [comment]
*[`android/pnddocs/flutter-android.md` line 133 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5lGZ9g9k7ZU0K8WqBW:-O6N_ekr5PJKee4K2V31:b-ip352b) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L133)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

מwhat is addRouterToPendoObserver()??
</blockquote></details>

the old one removing it

**Comment by MikePendo** [comment]
*[`android/pnddocs/flutter-android.md` line 155 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5lSu3Z2B9-D38vLakO:-O6NaFMtCdTQm_BcApp6:b-fahfoi) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L155)):*
<details><summary><i>Previously, DavidPendo wrote…</i></summary><blockquote>

We can point here to have a RouterConfig variable i.e
```
final RouterConfig _routerConfig = AppRouter().config()...addPendoListenerToDelegate();
```
</blockquote></details>

I dont know tried to stick more to auto_rourte docs:https://pub.dev/packages/auto_route:
```
class App extends StatelessWidget {
  // make sure you don't initiate your router
  // inside of the build function.
  final _appRouter = AppRouter();

  @override
  Widget build(BuildContext context){
    return MaterialApp.router(
      routerConfig: _appRouter.config(),
    );
  }
}
```

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: all files reviewed, 4 unresolved discussions (waiting on @DavidPendo, @MikePendo, @noambartouv, and @udilevin)

___
*[`ios/pnddocs/expo_router-ios.md` line 134 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6RLDQ17LY2HYUlkgT6:-O6RLDQ17LY2HYUlkgT7:biiktza) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/baeafeeb29601dbdbbf196f8cf0e4e372d10c1f1/ios/pnddocs/expo_router-ios.md#L134)):*
> ```Markdown
> and change your integration to the following:
> ```typescript
> export default WithPendoExpoRouter(RootLayout, {nativeIDs:["myProp"]});
> ```

why is this here?....

**Comment by udilevin** [comment]
*[`ios/pnddocs/expo_router-ios.md` line 134 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6RLDQ17LY2HYUlkgT6:-O6RLRNh-ktBYBrI-Xf1:b5e1xeh) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/baeafeeb29601dbdbbf196f8cf0e4e372d10c1f1/ios/pnddocs/expo_router-ios.md#L134)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

why is this here?....
</blockquote></details>

because it's wrong and @MikePendo fixed it :-)

**Comment by pendo-ops** [comment]
There was an error adding Reviewers to the Issue APP-108222: An error occured while trying to look up the Jira ticket APP-108222: jira api returned a 429 status code. Please retry request in 112 second(s)

**Review by noambartouv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: all files reviewed, 8 unresolved discussions (waiting on @DavidPendo and @MikePendo)

___
*[`README.md` line 55 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6RMc6CAwOiy80oUJOA:-O6RMc6CAwOiy80oUJOB:b-njyiec) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/baeafeeb29601dbdbbf196f8cf0e4e372d10c1f1/README.md#L55)):*
> ```Markdown
> 
> 
> ## Additional resources 
> ```

While it's mentioned in the bottom of the page. I think let's also add the offline support article to the end of the additional resources list here
___
*[`README.md` line 111 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6RMWAW-Td3XCvCH5vu:-O6RMWAW-Td3XCvCH5vv:bwy042w) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/baeafeeb29601dbdbbf196f8cf0e4e372d10c1f1/README.md#L111)):*
> ```Markdown
> **Offline support**
> 
> Additional information about offline support can be found in [Mobile offline support for analytics article](https://support.pendo.io/hc/en-us/articles/360043016412-Mobile-offline-support-for-analytics)
> ```

Missing "." at the end of the sentence (without hyperlink).
___
*[`android/pnddocs/flutter-android.md` line 124 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5UavXnCSuuShcyh0OC:-O6RO33wET7X_xFK-99D:b-5f0qkz) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L124)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

you think it still should be in front ?
</blockquote></details>

Debating - because of customer is scooping out if they can use our SDK I don't know that they will scroll down and see it.

That's why I suggest to add it but mention "If using X: 13.0 or higher" 
___
*[`android/pnddocs/flutter-android.md` line 121 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6RN4Rd0w6DCJbm6WuI:-O6RN4Rd0w6DCJbm6WuJ:b-bdgpj4) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/baeafeeb29601dbdbbf196f8cf0e4e372d10c1f1/android/pnddocs/flutter-android.md#L121)):*
> ```Markdown
>         ],);
>     ```
>     >[!NOTE] Pendo SDK uses the `Route` name to uniquely identify each `Route`. For the best practice please make sure 
> ```

Please look at the github actual visual - this looks broken

https://github.com/pendo-io/pendo-mobile-sdk/blob/APP-108222_simplified_integration/android/pnddocs/flutter-android.md#step-2-pendo-sdk-integration
___
*[`android/pnddocs/flutter-android.md` line 121 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6RNbXM6XW_p77wIKTT:-O6RNbXM6XW_p77wIKTU:bmicylj) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/baeafeeb29601dbdbbf196f8cf0e4e372d10c1f1/android/pnddocs/flutter-android.md#L121)):*
> ```Markdown
>         ],);
>     ```
>     >[!NOTE] Pendo SDK uses the `Route` name to uniquely identify each `Route`. For the best practice please make sure 
> ```

Grammar fix: "The Pendo SDK instead" of "Pendo SDK"
___
*[`android/pnddocs/flutter-android.md` line 122 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6RNeLgA2dZAwxEgSM7:-O6RNeLgA2dZAwxEgSM8:bl2jx1r) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/baeafeeb29601dbdbbf196f8cf0e4e372d10c1f1/android/pnddocs/flutter-android.md#L122)):*
> ```Markdown
>     ```
>     >[!NOTE] Pendo SDK uses the `Route` name to uniquely identify each `Route`. For the best practice please make sure 
>     to provide each route with unique name in the `RouteSettings`
> ```

End sentence with "."

**Review by noambartouv — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 4 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @DavidPendo, @MaximShnirman, @MikePendo, and @udilevin)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-:-O6gB-IwE0OFzbmr0YzW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DavidPendo)

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DavidPendo)

**Comment by udilevin** [comment]
:lgtm:

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DavidPendo)

**Comment by MikePendo** [comment]
*[`android/pnddocs/flutter-android.md` line 124 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O5UavXnCSuuShcyh0OC:-O6uUghlBH9ueNks-TWG:b-974peb) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a262eac9cb04e6730ea5e8702369f57e9a1335bc/android/pnddocs/flutter-android.md#L124)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Debating - because of customer is scooping out if they can use our SDK I don't know that they will scroll down and see it.

That's why I suggest to add it but mention "If using X: 13.0 or higher"
</blockquote></details>

@noambartouv I think I moved it

**Comment by DavidPendo** [comment]
*[`android/pnddocs/flutter-android.md` line 147 at r6](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6txjtcBsaKCvyvjl5G:-O6txjtcBsaKCvyvjl5H:bljm8q5) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/5efa0fb4e83e01140a4171bcb0390ce9ba3d8ae2/android/pnddocs/flutter-android.md#L147)):*
> ```Markdown
>     ```
> 
>     > Pendo SDK uses routerDelegate listener to track route change analytics, make sure your route is included in the GoRouter routes 
> ```

This section is dark and does not look good... Maybe better will be to use the \>\[!TIP\]

**Review by DavidPendo — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 3 files at r3, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: all files reviewed, 2 unresolved discussions (waiting on @MikePendo)

___
*[`android/pnddocs/flutter-android.md` line 18 at r6](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6txHnr559oP25K_aeV:-O6txHnr559oP25K_aeW:b87twpc) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/5efa0fb4e83e01140a4171bcb0390ce9ba3d8ae2/android/pnddocs/flutter-android.md#L18)):*
> ```Markdown
> >- minSdkVersion `21` or higher
> >- compileSDKVersion `33` or higher\
> >Supported Navigation Libraries:
> ```

Maybe the **Navigation Libraries** requirements should be near the relevant section

**Comment by MikePendo** [comment]
*[`android/pnddocs/flutter-android.md` line 147 at r6](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171#-O6txjtcBsaKCvyvjl5G:-O6ux0-BDW65toFmBi4Y:b18ccy7) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/5efa0fb4e83e01140a4171bcb0390ce9ba3d8ae2/android/pnddocs/flutter-android.md#L147)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

let me see how its looks like
</blockquote></details>

changes all to TIPS IOS and android

**Comment by DavidPendo** [comment]
[merge]

**Review by udilevin — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/171)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-108222](https://pendo-io.atlassian.net/browse/APP-108222): Jira Issue APP-108222: Changed to Resolved


Branch APP-108222_simplified_integration deleted

**Pull request merged**
