### PR TITLE
APP-83445

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/48)

### CODE REVIEW

**Review by noambartouv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/48)* status: all files reviewed, 2 unresolved discussions (waiting on @MikePendo)

___
*[`ios/pnddocs/swiftui.md` line 116 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/48#-NXqH13pAHr1y-dfDbTz:-NXqH13pAHr1y-dfDbU-:bv3bovw) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/57457fa5ac04b906c5c87726146a4f7873994715/ios/pnddocs/swiftui.md#L116)):*
> ```Markdown
> 
> ## Limitation 
> :technologist: - Dynamic Content (content that appears after your screen was loaded, a button click that triggers new elements to appear inside the same screen) currently not supported, please use `screenContentChanged` api for such screens. <br>
> ```

Dynamic Content (content that appears the screen has loaded, e.x. new elements or updated texts on the screen that appear as a result of a button clicked on the screen) is currently not supported. Please use the `screenContentChanged` API for such scenarios.
___
*[`ios/pnddocs/swiftui.md` line 121 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/48#-NXqHgPN0KRKFB2coNYt:-NXqHgPN0KRKFB2coNYu:b-7vxsv1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/57457fa5ac04b906c5c87726146a4f7873994715/ios/pnddocs/swiftui.md#L121)):*
> ```Markdown
> :technologist: - SwiftUI IOS 16 navigation api's not supported yet.
> 
> In general clickable elements should be tagged by default, but if clickable element is not taggable please apply the following api `.enableClickAnalytics()` on your view
> ```

Generally, all clickable elements should be taggable. In case you encounter a clickable element that you are not able to tag, please apply the  `.enableClickAnalytics()` API on this element.

**Review by udilevin — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/48)* status: all files reviewed, 2 unresolved discussions (waiting on @MikePendo)

**Review by udilevin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/48#-:-NY-5kS09TRYE30MqeBs:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @MikePendo)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/48#-:-NY-7LdK7feGvcbawLOx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by noambartouv** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-83445](https://pendo-io.atlassian.net/browse/APP-83445): Jira Issue APP-83445: Changed to Resolved


Branch APP-83445 deleted

**Pull request merged**
