### PR TITLE
APP-93557 documentation improvements

### PR DESCRIPTION
**Pull request by noambartouv**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/94)

### CODE REVIEW

**Review by udilevin — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues have missing required fields:
* [APP-93557](https://pendo-io.atlassian.net/browse/APP-93557): The Manual tests field is missing a value

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-93557](https://pendo-io.atlassian.net/browse/APP-93557): Jira Issue APP-93557: Changed to Resolved


Branch APP-93557-doc-improvements deleted

**Pull request merged**
