### PR TITLE
APP-101987 fix swift package

### PR DESCRIPTION
**Pull request by 0xkuj**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/141)

### CODE REVIEW

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @0xkuj)

**Review by orendayan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/141#-:-NxfysQZ21tcGn3Nhz65:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @0xkuj)

**Comment by orendayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues have missing required fields:
* [APP-101987](https://pendo-io.atlassian.net/browse/APP-101987): The Manual tests field is missing a value

**Comment by orendayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-101987](https://pendo-io.atlassian.net/browse/APP-101987): Jira Issue APP-101987: Changed to Resolved


Branch APP-101987_fix_swift_update deleted

**Pull request merged**
