### PR TITLE
APP-99209 add .NET 8 support to docs

### PR DESCRIPTION
**Pull request by noambartouv**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/127)

### CODE REVIEW

**Review by shlomipendo — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/127)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Review by udilevin — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/127)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Comment by udilevin** [comment]
:lgtm:

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-99209](https://pendo-io.atlassian.net/browse/APP-99209): Jira Issue APP-99209: Changed to Resolved


Branch APP-99209-add-.NET8 deleted

**Pull request merged**
