### PR TITLE
Update Package.swift

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/54)

### CODE REVIEW

**Review by 0xkuj — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Review by Betty42 — APPROVED** [review]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-84629](https://pendo-io.atlassian.net/browse/APP-84629): Invalid state 'Backlog' for merge into master

**Comment by Betty42** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-84629](https://pendo-io.atlassian.net/browse/APP-84629): Jira Issue APP-84629: Changed to Resolved


Branch APP-84629 deleted

**Pull request merged**
