### PR TITLE
APP-91991 Docs for SDK 3.0

### PR DESCRIPTION
**Pull request by noambartouv**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/75)

### CODE REVIEW

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Review by randmaayan — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/75)* status: all files reviewed, 1 unresolved discussion (waiting on @noambartouv)

___
*[`README.md` line 14 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/75#-NiVFN8aBNq3HWbyVfZA:-NiVFN8aBNq3HWbyVfZB:b-vrfgou) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/1825c5526daccd5d160c36555ab9f857ff8efa8f/README.md#L14)):*
> ```Markdown
> ## Integration Instructions 
> 
> The following integration insructions are relevant for SDK 3.0 or higher. Follow our migration instructions to [upgrade from SDK 2.x to 3.0](TODO:missing-link) or refer to our [2.x integration instruction](https://github.com/pendo-io/pendo-mobile-sdk/blob/2.22.5/README.md).
> ```

instructions. nb.

**Comment by randmaayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues need reviews:
* [APP-91991](https://pendo-io.atlassian.net/browse/APP-91991): Unknown value for the Data Privacy Review field.

**Comment by randmaayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issue transitions/labels succeeded, but some didn't.
Total number of issues: 1
Issues that successfully transitioned/labeled: 0
Issues that weren't transitioned/labeled: 0
Problems encountered:


Branch APP-91991-flat-hierarchy deleted

**Review by TehilaTaub — COMMENTED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/75#-:-Nie7foFAU-jtq8l8svN:b3sq3yz)* status: all files reviewed, 1 unresolved discussion

**Comment by pendo-ops** [comment]
This pull request is not mergeable. Make sure status checks are passing.

**Pull request merged**
