### PR TITLE
APP-88062 adding some scene delegate documentation

### PR DESCRIPTION
**Pull request by MaximShnirman**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71)

### CODE REVIEW

**Comment by udilevin** [comment]
*[`ios/pnddocs/native-ios.md` line 80 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71#-Nd54KDwDFCSZYy3xdB3:-Nd54KDwDFCSZYy3xdB4:b-g2fg6c) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/e330027065c584d35ed349276d48f903c5676401/ios/pnddocs/native-ios.md#L80)):*
> ```Markdown
>     PendoManager.shared().startSession("visitor1", accountId: "account1", visitorData:[], accountData: [])
> ```
> ```

this is the wrong objectivec implementation. You need scene willConnectTo and not openURL

**Comment by udilevin** [comment]
*[`ios/pnddocs/swiftui.md` line 58 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71#-Nd54YPj6Zr6baD_M_SH:-Nd54YPj6Zr6baD_M_SI:bk91bx4) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/e330027065c584d35ed349276d48f903c5676401/ios/pnddocs/swiftui.md#L58)):*
> ```Markdown
> }
> ```
> ```

what about openURL? Will that work with Scenes? @MikePendo

**Comment by MaximShnirman** [comment]
*[`ios/pnddocs/native-ios.md` line 80 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71#-Nd54KDwDFCSZYy3xdB3:-Nd5Rill-gLx3VtqJtV4:b-op1me2) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/e330027065c584d35ed349276d48f903c5676401/ios/pnddocs/native-ios.md#L80)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

this is the wrong objectivec implementation. You need scene willConnectTo and not openURL
</blockquote></details>

wait, the top one is to run setup call, the bottom is for open URL... what do I miss?

**Comment by MaximShnirman** [comment]
*[`ios/pnddocs/native-ios.md` line 80 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71#-Nd54KDwDFCSZYy3xdB3:-Nd5SdG51akjaL8872LH:b3p3yb1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/e330027065c584d35ed349276d48f903c5676401/ios/pnddocs/native-ios.md#L80)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

wait, the top one is to run setup call, the bottom is for open URL... what do I miss?
</blockquote></details>

i see now

**Comment by MikePendo** [comment]
*[`ios/pnddocs/swiftui.md` line 58 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71#-Nd54YPj6Zr6baD_M_SH:-Nd6GwYG7E4aJtk_zZnu:b7sqfof) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/e330027065c584d35ed349276d48f903c5676401/ios/pnddocs/swiftui.md#L58)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

what about openURL? Will that work with Scenes? @MikePendo
</blockquote></details>

 in our current Implementation we directly call the open url of the app delegate in swift ui. not the scene one.

**Comment by MaximShnirman** [comment]
*[`ios/pnddocs/swiftui.md` line 58 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71#-Nd54YPj6Zr6baD_M_SH:-NdTvYgy1zucc8JG9679:b9uh5h5) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/e330027065c584d35ed349276d48f903c5676401/ios/pnddocs/swiftui.md#L58)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

in our current Implementation we directly call the open url of the app delegate in swift ui. not the scene one.
</blockquote></details>

i think we should keep both for maybe more advanced users? WDYT?

**Review by MaximShnirman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @MikePendo and @udilevin)

___
*[`ios/pnddocs/rnn-ios.md` line 119 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71#-Nd6HodS6ekuZBraEgEt:-NdTvq2p6C3vl1jFvmnJ:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a1ea8e96a69c4729a48dffb1db7867924ebe1bc2/ios/pnddocs/rnn-ios.md#L119)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

maybe `@import Pendo;` as we do it in all the rest of the places
</blockquote></details>

Done.

**Review by 0xkuj — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71)* status: all files reviewed, 3 unresolved discussions (waiting on @MikePendo and @udilevin)

**Comment by MikePendo** [comment]
*[`ios/pnddocs/swiftui.md` line 58 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71#-Nd54YPj6Zr6baD_M_SH:-Nd_ZURe4tFsqefasewn:b6x0hl9) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/e330027065c584d35ed349276d48f903c5676401/ios/pnddocs/swiftui.md#L58)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

i think we should keep both for maybe more advanced users? WDYT?
</blockquote></details>

I am not sure what I can add here, we need to look how to call scene delegates open url from swiftUI.

**Review by udilevin — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by udilevin** [comment]
:lgtm:

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-88062](https://pendo-io.atlassian.net/browse/APP-88062): Jira Issue APP-88062: Changed to Resolved


Branch APP-88062_openURL_ deleted

**Pull request merged**
