### PR TITLE
APP-85914 pendoOptions

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/61)

### CODE REVIEW

**Comment by udilevin** [comment]
:lgtm:

**Review by rotemelem6 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Comment by rotemelem6** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-85914](https://pendo-io.atlassian.net/browse/APP-85914): Resolved


Branch APP-85914_pendoOptions deleted

**Pull request merged**
