### PR TITLE
APP-109311_ios_notification_style2

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/178)

### CODE REVIEW

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/178#-:-O6bpyLS0I-YJ8-pWJWl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Review by 0xkuj — APPROVED** [review]

**Review by 0xkuj — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/178)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by noambartouv** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-109311](https://pendo-io.atlassian.net/browse/APP-109311): Jira Issue APP-109311: Changed to Resolved


Branch APP-109311_ios_notification_style2 deleted

**Pull request merged**
