### PR TITLE
APP-110402

### PR DESCRIPTION
**Pull request by 0xkuj**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/187)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[eb3a86a](https://github.com/pendo-io/pendo-mobile-sdk/pull/187/commits/eb3a86a3c3883b70ddbda471fc77ed82d5b4ef33)

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/187)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @0xkuj)

**Comment by MaximShnirman** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch 0xkuj-patch-2 deleted

**Pull request merged**
