### PR TITLE
APP-83562_Bug_format

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49)

### CODE REVIEW

**Review by noambartouv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @MikePendo)

___
*[`.github/ISSUE_TEMPLATE/bug_report.md` line 2 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-NXvTr7F8LIGH0fW1en9:-NXvTr7F8LIGH0fW1enA:b-5kvfoy) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c455ca564ca69c796859daee39d751462c265738/.github/ISSUE_TEMPLATE/bug_report.md#L2)):*
> ```Markdown
> ---
> name: Bug report
> ```

What is this first section? What do you expect the customer to write in these first fields apart from the title? What is assignees for example?
___
*[`.github/ISSUE_TEMPLATE/bug_report.md` line 21 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-NXvTgzy7TkDrYC9kqAn:-NXvTgzy7TkDrYC9kqAo:b1le4la) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c455ca564ca69c796859daee39d751462c265738/.github/ISSUE_TEMPLATE/bug_report.md#L21)):*
> ```Markdown
>  Xamarin, XamarinForms, Maui,<br>
>  Flutter
> ```

I would ask for SDK versions as well 
___
*[`.github/ISSUE_TEMPLATE/bug_report.md` line 36 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-NXvUQTXDxQYgCy1aPir:-NXvUQTXDxQYgCy1aPis:bo70ut8) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c455ca564ca69c796859daee39d751462c265738/.github/ISSUE_TEMPLATE/bug_report.md#L36)):*
> ```Markdown
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> ```

Do we expect crashes to be reported in github? Do we want to ask for crash log if applicable?
___
*[`.github/ISSUE_TEMPLATE/bug_report.md` line 38 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-NXvUYZkEC8jvQ6W7mu8:-NXvUYZkEC8jvQ6W7mu9:b-1sql79) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c455ca564ca69c796859daee39d751462c265738/.github/ISSUE_TEMPLATE/bug_report.md#L38)):*
> ```Markdown
> If applicable, add screenshots to help explain your problem.
> 
> **Sample Code**
> ```

Optional maybe: Link to appstore / play store?

**Comment by MikePendo** [comment]
*[`.github/ISSUE_TEMPLATE/bug_report.md` line 21 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-NXvTgzy7TkDrYC9kqAn:-NXvX1d3-TayH4ZLrZdQ:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c455ca564ca69c796859daee39d751462c265738/.github/ISSUE_TEMPLATE/bug_report.md#L21)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

I would ask for SDK versions as well 
</blockquote></details>

Done

**Comment by MikePendo** [comment]
*[`.github/ISSUE_TEMPLATE/bug_report.md` line 36 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-NXvUQTXDxQYgCy1aPir:-NXvXPkp8kHFFDqA3cuT:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c455ca564ca69c796859daee39d751462c265738/.github/ISSUE_TEMPLATE/bug_report.md#L36)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Do we expect crashes to be reported in github? Do we want to ask for crash log if applicable?
</blockquote></details>

Done

**Comment by MikePendo** [comment]
*[`.github/ISSUE_TEMPLATE/bug_report.md` line 38 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-NXvUYZkEC8jvQ6W7mu8:-NXvXUu1AW3Onqiy-s8B:b-6w066j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c455ca564ca69c796859daee39d751462c265738/.github/ISSUE_TEMPLATE/bug_report.md#L38)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Optional maybe: Link to appstore / play store?
</blockquote></details>

Didn't see it used, as its public to all people (don't think its good idea)

**Comment by MikePendo** [comment]
*[`.github/ISSUE_TEMPLATE/bug_report.md` line 2 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-NXvTr7F8LIGH0fW1en9:-NXvY06_7puVs5bzxNON:bcvgxdl) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c455ca564ca69c796859daee39d751462c265738/.github/ISSUE_TEMPLATE/bug_report.md#L2)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

What is this first section? What do you expect the customer to write in these first fields apart from the title? What is assignees for example?
</blockquote></details>

I think its not part of the report, i.e GitHub created a title from it (we will see how it looks like)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49#-:-NXvYhoL1R6bCd6VHmtt:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by orendayan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-83562](https://pendo-io.atlassian.net/browse/APP-83562): Jira Issue APP-83562: Changed to Resolved


Branch APP-83562 deleted

**Pull request merged**
