### PR TITLE
APP-108711 formatting benchmark files

### PR DESCRIPTION
**Pull request by MaximShnirman**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180)

### CODE REVIEW

**Comment by MikePendo** [comment]
*[`benchmarks/FlutterPerformanceBenchmarks.md` line 10 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6uagH_8pbvJ3cVuN9n:-O6uagH_8pbvJ3cVuN9o:b-i9mhb5) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/benchmarks/FlutterPerformanceBenchmarks.md#L10)):*
> ```Markdown
> |     :---:      |     :---:   |     :---:     |    :---:     |   
> |    Flutter     |    103 KB   | (~) 60-200KB  |   (~) 10%    |
> ```

how that possible that size on native will be that much bigger than the size on flutter(x20), eventually its the same binary?

**Comment by udilevin** [comment]
*[`benchmarks/FlutterPerformanceBenchmarks.md` line 10 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6uagH_8pbvJ3cVuN9n:-O6vDP0k8JSMWZhACW4q:bqn8hoe) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/benchmarks/FlutterPerformanceBenchmarks.md#L10)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

how that possible that size on native will be that much bigger than the size on flutter(x20), eventually its the same binary?
</blockquote></details>

We should add the native size as well (6MB)

**Review by naorlevi — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180)* status: all files reviewed, 3 unresolved discussions (waiting on @DavidPendo, @MaximShnirman, @MikePendo, and @udilevin)

___
*[`benchmarks/FlutterPerformanceBenchmarks.md` line 9 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6wNgrmEE2h8-ZSbJqO:-O6wNgrmEE2h8-ZSbJqP:b-3oo7sg) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/benchmarks/FlutterPerformanceBenchmarks.md#L9)):*
> ```Markdown
> |                | Size Impact | Memory Impact | CPU Impact\* |
> |     :---:      |     :---:   |     :---:     |    :---:     |   
> |    Flutter     |    103 KB   | (~) 60-200KB  |   (~) 10%    |
> ```

Is 10% considered low? medium? In the Native benchmark we just mention low which is a bit easier to grasp.

**Comment by MaximShnirman** [comment]
*[`README.md` line 74 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6u_wTABPMBEQWTTqDD:-O6yl8WjBoKxndUKJn33:b-2rbvug) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/README.md#L74)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

that doesnt work (maybe it should be relative). please verify on GitHub
</blockquote></details>

this doesnt work cause its on a side branch and not on the main branch AFAIK

**Comment by MaximShnirman** [comment]
*[`benchmarks/FlutterPerformanceBenchmarks.md` line 9 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6wNgrmEE2h8-ZSbJqO:-O6ylFLK92G7ziS6NP_x:b-46p9fi) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/benchmarks/FlutterPerformanceBenchmarks.md#L9)):*
<details><summary><i>Previously, naorlevi (pippoTLV) wrote…</i></summary><blockquote>

Is 10% considered low? medium? In the Native benchmark we just mention low which is a bit easier to grasp.
</blockquote></details>

right, tho here we do not have that data. what do you suggest?

**Review by MaximShnirman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180)* status: all files reviewed, 3 unresolved discussions (waiting on @DavidPendo, @MikePendo, @naorlevi, and @udilevin)

___
*[`benchmarks/FlutterPerformanceBenchmarks.md` line 10 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6uagH_8pbvJ3cVuN9n:-O6ylMM29h5yR5YM5zrQ:b-qnupcj) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/benchmarks/FlutterPerformanceBenchmarks.md#L10)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

We should add the native size as well (6MB)
</blockquote></details>

native side data appear on native file (link is at the bottom)
size wise - yes, this is the size

**Comment by DavidPendo** [comment]
*[`README.md` line 74 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6u_wTABPMBEQWTTqDD:-O6z9hB9-upKTzZ5ZA3f:bdctv72) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/README.md#L74)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

this doesnt work cause its on a side branch and not on the main branch AFAIK
</blockquote></details>

@MaximShnirman, it should be a relative path

**Comment by DavidPendo** [comment]
*[`benchmarks/FlutterPerformanceBenchmarks.md` line 9 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6wNgrmEE2h8-ZSbJqO:-O6zArKKBiuOwh9UEZZf:b-r6g2lu) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/benchmarks/FlutterPerformanceBenchmarks.md#L9)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

right, tho here we do not have that data. what do you suggest?
</blockquote></details>

Let's use the same approach as for native using verbose description **LOW**

**Review by DavidPendo — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180)* status: all files reviewed, 3 unresolved discussions (waiting on @MaximShnirman, @MikePendo, @naorlevi, and @udilevin)

**Review by MaximShnirman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180)* status: all files reviewed, 2 unresolved discussions (waiting on @MikePendo, @naorlevi, and @udilevin)

___
*[`README.md` line 74 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6u_wTABPMBEQWTTqDD:-O6zEAF48BoYt86B-wiI:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/README.md#L74)):*
<details><summary><i>Previously, DavidPendo wrote…</i></summary><blockquote>

@MaximShnirman, it should be a relative path
</blockquote></details>

Done.

**Comment by MaximShnirman** [comment]
*[`benchmarks/FlutterPerformanceBenchmarks.md` line 10 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6uagH_8pbvJ3cVuN9n:-O6zeLFb43NLAFlV4Ck0:b-7rl0kd) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/d7c34de8e9a0f101c20f853e6d0abf1403d55da0/benchmarks/FlutterPerformanceBenchmarks.md#L10)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

native side data appear on native file (link is at the bottom)
size wise - yes, this is the size
</blockquote></details>

done

**Comment by MikePendo** [comment]
*[`benchmarks/FlutterPerformanceBenchmarks.md` line 12 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180#-O6zeWYZ4NOB2gMYPcAq:-O6zeWY_8ARghQZlMcaJ:bc3lt6s) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/4e60b1374807146fc5c17373864e10c6f2d455b0/benchmarks/FlutterPerformanceBenchmarks.md#L12)):*
> ```Markdown
> 
> <b>\*</b> Slight CPU impact may occur during app launch or UI-intensive operations.
> <b>\*\*</b> 103KB reffers to the Flutter plugin size while iOS native SDK size is ~6MB, Android native SDK size is ~3MB.
> ```

non blocking BUT I still think it should be more clear (i.e like native), in the end the flutter devs should see exactly how much it adds to their final app and not look for it between the lines

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180)* status: all files reviewed, 1 unresolved discussion (waiting on @MaximShnirman and @naorlevi)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-108711](https://pendo-io.atlassian.net/browse/APP-108711): Jira Issue APP-108711: Changed to Resolved


Branch APP-108711_benchmarks deleted

**Pull request merged**
