### PR TITLE
APP-109723

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/182)

### CODE REVIEW

**Review by MaximShnirman — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/182)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @MikePendo)

**Review by DavidPendo — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/182)* status: all files reviewed, 1 unresolved discussion (waiting on @MikePendo)

___
*[`ios/pnddocs/flutter-ios.md` line 12 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/182#-O7NVfRu5uDGefGZprpb:-O7NVfRu5uDGefGZprpc:b-lg5nfh) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a389dcc1b4749e5f60daf36e063ecfa7a5ac258c/ios/pnddocs/flutter-ios.md#L12)):*
> ```Markdown
> >Requirements:
> >- Flutter: ">=3.16.0"
> >- SDK: ">=3.2.0 < 4.0.0"git 
> ```

What is **git**? The same SDK requirement is for Android too, so you if there is some changes it should be for both files

**Comment by MaximShnirman** [comment]
*[`ios/pnddocs/flutter-ios.md` line 12 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/182#-O7NVfRu5uDGefGZprpb:-O7ODUmI4nEpzUvrKv6h:b-25wb89) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a389dcc1b4749e5f60daf36e063ecfa7a5ac258c/ios/pnddocs/flutter-ios.md#L12)):*
<details><summary><i>Previously, DavidPendo wrote…</i></summary><blockquote>

What is **git**? The same SDK requirement is for Android too, so you if there is some changes it should be for both files
</blockquote></details>

i assume this is a mistake? (the git string)

**Review by DavidPendo — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by DavidPendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-109723](https://pendo-io.atlassian.net/browse/APP-109723): Jira Issue APP-109723: Changed to Resolved


Branch APP-109723 deleted

**Pull request merged**
