### PR TITLE
APP-82169 added missing instructions

### PR DESCRIPTION
**Pull request by orendayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)

### CODE REVIEW

**Comment by MikePendo** [comment]
*[`ios/pnddocs/rnn-ios.md` line 26 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW55eujCy2t7oNmKZsd:-NW55euk0iaXL2SfrEII:b-506em3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L26)):*
> ```Markdown
> 3. #### Add a **bridging header** as described in <a href="https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift" target="_blank">this Apple documentation</a>.
>     Add the following import statement to the bridging header:  
>     `@import Pendo;`
> ```

@orendayan I know its not your pr BUT @udilevin can u please remind me why we need that step?

**Comment by MikePendo** [comment]
*[`ios/pnddocs/rnn-ios.md` line 102 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW574lw-kANZiLEaD2o:-NW574lw-kANZiLEaD2p:b-j85cph) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L102)):*
> ```Markdown
>       Under App Target > Info > URL Types, create a new URL by clicking the + button.  
>       Set **Identifier** to pendo-pairing or any name of your choosing.  
>       Set **URL Scheme** to `YOUR_SCHEME_HERE`.
> ```

@udilevin there were an image with steps explanation (at least we still have it in native). That explains it. I am not sure why u have removed it

**Comment by orendayan** [comment]
*[`ios/pnddocs/rnn-ios.md` line 108 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW56C950GSpwgggnoLM:-NW6DUA347vG9vf0vyd_:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L108)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@orendayan lets have a better explanation in 2. like "In Appdelegate file import Pendo and change application:openURL:options". Otherwise its not clear where the import is going to?
</blockquote></details>

Done.

**Comment by udilevin** [comment]
*[`ios/pnddocs/rnn-ios.md` line 26 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW55eujCy2t7oNmKZsd:-NW761Oc7yhWDgyWfJ5z:b-fdfseo) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L26)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@orendayan I know its not your pr BUT @udilevin can u please remind me why we need that step?
</blockquote></details>

Don't think we need it for RN/RNN

**Comment by udilevin** [comment]
*[`ios/pnddocs/rnn-ios.md` line 102 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW574lw-kANZiLEaD2o:-NW77fdYCt5157rHGNm_:bqxrgxn) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L102)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@udilevin there were an image with steps explanation (at least we still have it in native). That explains it. I am not sure why u have removed it
</blockquote></details>

There were no images in rn/rnn.

**Comment by MikePendo** [comment]
*[`ios/pnddocs/rnn-ios.md` line 26 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW55eujCy2t7oNmKZsd:-NW8EyfG81WPjuI4dv1r:bdz77b) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L26)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Don't think we need it for RN/RNN
</blockquote></details>

@orendayan please lets remove it

**Comment by MikePendo** [comment]
*[`ios/pnddocs/rnn-ios.md` line 102 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW574lw-kANZiLEaD2o:-NW8FSlY8yNzTXFQPbir:b54b1ob) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L102)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

There were no images in rn/rnn.
</blockquote></details>

**Comment by MikePendo** [comment]
*[`ios/pnddocs/rnn-ios.md` line 108 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW56C950GSpwgggnoLM:-NW8GZXr5OMPVvCnuWhV:b-pw2cj0) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L108)):*
<details><summary><i>Previously, orendayan (Oren Dayan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`In Appdelegate file import Pendo and add or modify the function application:openURL:options:`
That's sounds better AND lets remove this comment `//for objc++(.mm file) please add this import`
As it will be done for objc and objc++ (just make sure it works for objc the same way it works in objc ++)
if not we will need to split  split `@import Pendo` for objc and and `#import <Pendo/Pendo.h>` for objc++

**Comment by udilevin** [comment]
*[`ios/pnddocs/rnn-ios.md` line 108 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW56C950GSpwgggnoLM:-NWBr0oyC_jT6RB2ePAv:b-i51suk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L108)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

`In Appdelegate file import Pendo and add or modify the function application:openURL:options:`
That's sounds better AND lets remove this comment `//for objc++(.mm file) please add this import`
As it will be done for objc and objc++ (just make sure it works for objc the same way it works in objc ++)
if not we will need to split  split `@import Pendo` for objc and and `#import <Pendo/Pendo.h>` for objc++
</blockquote></details>

@orendayan make sure you send these changes to @juliebenjamin to approve the language changes.

**Review by orendayan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @0xkuj, @juliebenjamin, @MaximShnirman, @MikePendo, and @udilevin)

___
*[`ios/pnddocs/rnn-ios.md` line 26 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW55eujCy2t7oNmKZsd:-NWChVf7-ffnxkT0L-ta:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L26)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@orendayan please lets remove it
</blockquote></details>

Done.

**Comment by MikePendo** [comment]
*[`ios/pnddocs/native-ios.md` line 46 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NWE5n52EjyyY9d64kjY:-NWE5n52EjyyY9d64kjZ:bc1288d) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/badc0ef3b318a16ad13aa0588da7000d08bbc85f/ios/pnddocs/native-ios.md#L46)):*
> ```Markdown
>     @interface AppDelegate ()
>     @end
>     
> ```

```
   @interface AppDelegate ()
    @end
```
redundant

**Comment by MikePendo** [comment]
*[`ios/pnddocs/rnn-ios.md` line 108 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW56C950GSpwgggnoLM:-NWE6O5eCnmdsnAXTw--:b-99ueo4) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L108)):*
<details><summary><i>Previously, orendayan (Oren Dayan) wrote…</i></summary><blockquote>

@MikePendo really don't know what you meant here 
</blockquote></details>

your instruction says: 
`#### In AppDelegate file add or modify the function**application:openURL:options**:`
and on the next line you are showing the following code:
```objective-c
   //for objc++(.mm file) please add this import
   #import <Pendo/Pendo.h>
```
lets change the instruction to:
`In Appdelegate file import Pendo and add or modify the function application:openURL:options:`
And I think its better not to confuse customers with objc++ comments, so we can remove the comment about it, just verify the same import will work on objc

**Comment by MikePendo** [comment]
:lgtm:

**Review by MikePendo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @0xkuj, @MaximShnirman, @orendayan, and @udilevin)

**Review by orendayan — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-:-NWH54B-62PTVAnkiCcG:bnfp4nl)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @0xkuj, @MaximShnirman, and @udilevin)

**Review by orendayan — COMMENTED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: all files reviewed, 1 unresolved discussion (waiting on @0xkuj, @MaximShnirman, and @udilevin)

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues need reviews:
* [APP-82196](https://pendo-io.atlassian.net/browse/APP-82196): Needs Senior Review

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch merge failed. At least 2 approving reviews are required by reviewers with write access.

**Review by udilevin — COMMENTED** [review]
> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @0xkuj, @MaximShnirman, and @orendayan)

___
*[`ios/pnddocs/rnn-ios.md` line 102 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NW574lw-kANZiLEaD2o:-NWBqsi8DnET04FshHJe:b-oe8vmv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/45112f431233213a25ac96828aefaacac1a01434/ios/pnddocs/rnn-ios.md#L102)):*
> There were no images in rn/rnn.

**Review by udilevin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: all files reviewed, 1 unresolved discussion (waiting on @0xkuj, @MaximShnirman, and @orendayan)

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: all files reviewed, 3 unresolved discussions (waiting on @0xkuj and @orendayan)

___
*[`ios/pnddocs/flutter-ios.md` line 13 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NWgpk6l2AyFjCW9RHkg:-NWgpk6l2AyFjCW9RHkh:b-ta63fm) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/6ad90f59c04e3bbfee5494d21dd472cfed4960d7/ios/pnddocs/flutter-ios.md#L13)):*
> ```Markdown
>     import 'package:pendo_sdk/pendo_sdk.dart';
>     var pendoKey = 'YOUR_APPKEY_HERE';
>     await PendoFlutterPlugin.setup(pendoKey);
> ```

Why do setup and track requires await? 
___
*[`ios/pnddocs/native-ios.md` line 75 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NWgqFlIBxqOFj443PM_:-NWgqFlIBxqOFj443PMa:b6d9ifs) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/6ad90f59c04e3bbfee5494d21dd472cfed4960d7/ios/pnddocs/native-ios.md#L75)):*
> ```Markdown
> Mobile Tagging
> 
> 2. #### In AppDelegate file add or modify the **openURL** function:
> ```

number 2 here as  'step 2'? if so, seems wrong

**Comment by udilevin** [comment]
*[`ios/pnddocs/flutter-ios.md` line 13 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43#-NWgpk6l2AyFjCW9RHkg:-NWh6scE6LTzCoysCBHx:b-7si6rv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/6ad90f59c04e3bbfee5494d21dd472cfed4960d7/ios/pnddocs/flutter-ios.md#L13)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

Why do setup and track requires await? 
</blockquote></details>

all needs await...fixed

**Review by udilevin — COMMENTED** [review]
> Reviewed 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: all files reviewed, 2 unresolved discussions (waiting on @0xkuj and @orendayan)

**Review by udilevin — COMMENTED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @0xkuj and @orendayan)

**Review by orendayan — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)* status: all files reviewed, 2 unresolved discussions (waiting on @0xkuj)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-82169](https://pendo-io.atlassian.net/browse/APP-82169): Jira Issue APP-82169: Changed to Resolved


Branch APP-82169 deleted

**Pull request merged**
