### PR TITLE
APP-111637 update about obfuscation + remove beta

### PR DESCRIPTION
**Pull request by MaximShnirman**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/199)

### CODE REVIEW

**Review by udilevin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaximShnirman)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues have missing required fields:
* [APP-111637](https://pendo-io.atlassian.net/browse/APP-111637): The Manual Verification on Staging field is missing a value

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issue transitions/labels succeeded, but some didn't.
Total number of issues: 1
Issues that successfully transitioned/labeled: 1
Issues that weren't transitioned/labeled: 1
Problems encountered:
* [APP-111637](https://pendo-io.atlassian.net/browse/APP-111637): Jira Issue APP-111637: Not changed to Resolved - Status code from JIRA was not successful. 400


Branch APP-111637_obfuscation_update deleted

**Pull request merged**
