### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by 0xkuj**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/64)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[92a4eda](https://github.com/pendo-io/pendo-mobile-sdk/pull/64/commits/92a4eda8a47aaa1a455eaf986e1e14696a244d39)

**Review by orendayan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0xkuj)

**Comment by orendayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-86158](https://pendo-io.atlassian.net/browse/APP-86158): Jira Issue APP-86158: Changed to Resolved


Branch APP-86158_update_docs_2.22.2 deleted

**Pull request merged**
