### PR TITLE
APP-85331 update scheme and app key to api and note where to find them

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/59)

### CODE REVIEW

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/59#-:-N_i6F7GAJfgyIYZ8f1-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Comment by noambartouv** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-85331](https://pendo-io.atlassian.net/browse/APP-85331): Jira Issue APP-85331: Changed to Resolved


Branch APP-85331_scheme_app_keys_update deleted

**Pull request merged**
