### PR TITLE
APP-84759 fix native docs

### PR DESCRIPTION
**Pull request by 0xkuj**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/55)

### CODE REVIEW

**Review by MaximShnirman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/55)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @0xkuj)

___
*[`ios/pnddocs/native-ios.md` line 12 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/55#-NZu_is2D-OAeio1SArJ:-NZu_is2D-OAeio1SArK:b-b5mkjk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/860955b775c4077025fc2732567614eb72fc9784/ios/pnddocs/native-ios.md#L12)):*
> ```Markdown
> _File -> Add Packages_ in the search window paste:
> 
> `https://github.com/pendo-io/pendo-mobile-sdk/ios`
> ```

this should be ios

**Review by MaximShnirman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/55)* status: 1 of 2 files reviewed, all discussions resolved

**Review by udilevin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0xkuj)

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-84759](https://pendo-io.atlassian.net/browse/APP-84759): Jira Issue APP-84759: Changed to Resolved


Branch APP-84759_fix_docs_native deleted

**Pull request merged**
