### PR TITLE
APP-113581 setup and startSession clarifications

### PR DESCRIPTION
**Pull request by 0xkuj**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/207)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[6bf10e0](https://github.com/pendo-io/pendo-mobile-sdk/pull/207/commits/6bf10e0e3528ae76fb2e03aa537244c561b373c4)

**Comment by naorlevi** [comment]
*[`api-documentation/native-ios-apis.md` line 81 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/207#-OD72apEBTVMk5aL4M_B:-OD72apEBTVMk5aL4M_C:b8ft27r) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/6bf10e0e3528ae76fb2e03aa537244c561b373c4/api-documentation/native-ios-apis.md#L81)):*
> ```Markdown
> ```
> 
> > Establishes a connection with Pendo’s server. Call this API in your application’s onCreate() method. The setup method can only be called once during the application lifecycle. Calling this API is required before tracking sessions or invoking session-related APIs.
> ```

this is incorrect. We talked about changing the android "onCreate()" to iOS methods

**Comment by naorlevi** [comment]
*[`api-documentation/native-ios-apis.md` line 639 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/207#-OD7360H-tc-XEQsozs5:-OD7360H-tc-XEQsozs6:blz93zs) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/6bf10e0e3528ae76fb2e03aa537244c561b373c4/api-documentation/native-ios-apis.md#L639)):*
> ```Markdown
> ## NSNotifications
> 
> ### `kPNDDidSuccessfullyInitializeSDKNotification`
> ```

we talked about changing the header to be SwiftUI convention and add a row in the description section about how it is named in Objective-C (for both notifications)

**Review by naorlevi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/207)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @0xkuj)

**Comment by naorlevi** [comment]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-113581](https://pendo-io.atlassian.net/browse/APP-113581): Invalid state 'Backlog' for merge into master

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-113581](https://pendo-io.atlassian.net/browse/APP-113581): Invalid state 'Dev Ready' for merge into master

**Comment by naorlevi** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-113581](https://pendo-io.atlassian.net/browse/APP-113581): Jira Issue APP-113581: Changed to Resolved


Branch APP-113581_ios_api_docs deleted

**Pull request merged**
