### PR TITLE
APP-106394 allProjects fix

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/160)

### CODE REVIEW

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/160#-:-O2eAXai289-gITlqmKu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Review by udilevin — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 6 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/160)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @noambartouv)

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-106394](https://pendo-io.atlassian.net/browse/APP-106394): Invalid state 'Backlog' for merge into master

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-106394](https://pendo-io.atlassian.net/browse/APP-106394): Jira Issue APP-106394: Changed to Resolved


Branch APP-106394_allProjects deleted

**Pull request merged**
