### PR TITLE
APP-111911 add NavigationLibrary to setup call

### PR DESCRIPTION
**Pull request by MaximShnirman**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/204)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[b343288](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/b3432887411f4e13a19afea953a9d8eec4655d80)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[b343288](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/b3432887411f4e13a19afea953a9d8eec4655d80)
[5780e85](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/5780e850702df2aa9d5c6e701d02299199c87ceb)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[b343288](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/b3432887411f4e13a19afea953a9d8eec4655d80)
[5780e85](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/5780e850702df2aa9d5c6e701d02299199c87ceb)
[e9833b2](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/e9833b2001f2de71a93c74644af7f6eee9c46904)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[b343288](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/b3432887411f4e13a19afea953a9d8eec4655d80)
[5780e85](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/5780e850702df2aa9d5c6e701d02299199c87ceb)
[e9833b2](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/e9833b2001f2de71a93c74644af7f6eee9c46904)
[4145c29](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/4145c29a69395a3aa61dc6619872b23cad2ee634)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[b343288](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/b3432887411f4e13a19afea953a9d8eec4655d80)
[5780e85](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/5780e850702df2aa9d5c6e701d02299199c87ceb)
[e9833b2](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/e9833b2001f2de71a93c74644af7f6eee9c46904)
[4145c29](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/4145c29a69395a3aa61dc6619872b23cad2ee634)
[92559e9](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/92559e9b8063bae0b1216cff04b9a9f351d844ab)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[b343288](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/b3432887411f4e13a19afea953a9d8eec4655d80)
[5780e85](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/5780e850702df2aa9d5c6e701d02299199c87ceb)
[e9833b2](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/e9833b2001f2de71a93c74644af7f6eee9c46904)
[4145c29](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/4145c29a69395a3aa61dc6619872b23cad2ee634)
[92559e9](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/92559e9b8063bae0b1216cff04b9a9f351d844ab)
[01fa7d5](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/01fa7d5e3fda0873615621b15d3d36e687f1fd31)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[b343288](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/b3432887411f4e13a19afea953a9d8eec4655d80)
[5780e85](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/5780e850702df2aa9d5c6e701d02299199c87ceb)
[e9833b2](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/e9833b2001f2de71a93c74644af7f6eee9c46904)
[4145c29](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/4145c29a69395a3aa61dc6619872b23cad2ee634)
[92559e9](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/92559e9b8063bae0b1216cff04b9a9f351d844ab)
[01fa7d5](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/01fa7d5e3fda0873615621b15d3d36e687f1fd31)
[fd88d6d](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/fd88d6df5ba3604fb84b04c58fe948f661aef95e)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[e271ee1](https://github.com/pendo-io/pendo-mobile-sdk/pull/204/commits/e271ee106063b812a023de2733a47bb56f7c4aa6)

**Review by DavidPendo — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/204)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaximShnirman)

**Review by udilevin — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/204)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaximShnirman)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-111911](https://pendo-io.atlassian.net/browse/APP-111911): Jira Issue APP-111911: Changed to Resolved


Branch APP-111911_navigationLibrary_type deleted

**Pull request merged**
