### PR TITLE
App 81788 android docs

### PR DESCRIPTION
**Pull request by udilevin**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/41)

### CODE REVIEW

**Review by cohenam — APPROVED** [review]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-81788](https://pendo-io.atlassian.net/browse/APP-81788): Invalid state 'Backlog' for merge into master

**Comment by cohenam** [comment]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-81788](https://pendo-io.atlassian.net/browse/APP-81788): Invalid state 'Dev Ready' for merge into master

**Comment by cohenam** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-81788](https://pendo-io.atlassian.net/browse/APP-81788): Jira Issue APP-81788: Changed to Resolved


Branch APP-81788 deleted

**Pull request merged**
