### PR TITLE
APP-105845 require setup to be called on app launch

### PR DESCRIPTION
**Pull request by noambartouv**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/156)

### CODE REVIEW

**Review by randmaayan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/156)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Comment by randmaayan** [comment]
[merge]

**Comment by randmaayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-105845](https://pendo-io.atlassian.net/browse/APP-105845): Jira Issue APP-105845: Changed to Resolved


Branch APP-105845 deleted

**Pull request merged**
