### PR TITLE
APP-102949 add expo router documentation

### PR DESCRIPTION
**Pull request by udilevin**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146)

### CODE REVIEW

**Review by noambartouv — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @udilevin)

___
*[`android/pnddocs/expo_router-android.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146#-NzYNfhq6e_GTgXBAeew:-NzYNfhq6e_GTgXBAeex:ba5is5a) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a76149d2d72a1266079a40385783b6de3f5cf478/android/pnddocs/expo_router-android.md#L7)):*
> ```Markdown
> >- **Expo Go** is not supported. Pendo SDK has a native plugin that is not part of the Expo Go app.
> Pendo can *only* be used in development builds. For more about development builds read [adding custom native code with development builds](https://docs.expo.dev/workflow/customizing/).
> ```

Let's add the android requirements note similar to expo-rn and expo-rnn
___
*[`ios/pnddocs/expo_router-ios.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146#-NzYOXjO0z2ljynjVVFz:-NzYOXjO0z2ljynjVVG-:b-b9w63o) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a76149d2d72a1266079a40385783b6de3f5cf478/ios/pnddocs/expo_router-ios.md#L7)):*
> ```Markdown
> >- **Expo Go** is not supported. Pendo SDK has a native plugin that is not part of the Expo Go app.
> Pendo can *only* be used in development builds. For more about development builds read [adding custom native code with development builds](https://docs.expo.dev/workflow/customizing/).
> ```

Let's add the ios requirements note similar to expo-rn and expo-rnn

**Review by randmaayan — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146)* status: all files reviewed, 1 unresolved discussion (waiting on @udilevin)

**Review by noambartouv — COMMENTED** [review]
> Reviewed 4 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @randmaayan and @udilevin)

**Review by randmaayan — APPROVED** [review]
> Reviewed 5 of 6 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146#-:-O0sVatyDBmOHg5t5JGg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Comment by randmaayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-102949](https://pendo-io.atlassian.net/browse/APP-102949): Jira Issue APP-102949: Changed to Resolved


Branch APP-102949 deleted

**Pull request merged**
