### PR TITLE
App 83565 native with flutter components

### PR DESCRIPTION
**Pull request by noambartouv**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)

### CODE REVIEW

**Review by udilevin — CHANGES_REQUESTED** [review]
> Reviewed 18 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: 18 of 19 files reviewed, 3 unresolved discussions (waiting on @noambartouv)

___
*[`other/native-with-flutter-components.md` line 28 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NuiSRl0C7nUuJWrpPBY:-NuiSRl0C7nUuJWrpPBZ:b-ree90k) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L28)):*
> ```Markdown
> In the `pubspec.yaml` file, add the Pendo plugin under the dependencies section:
> ```shell
> # make sure you are using the latest version. This is just an example:
> ```

should probably be 3.1 or even 3.2
___
*[`other/native-with-flutter-components.md` line 57 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NuiSX-HBovMuHCphd6q:-NuiSX-HBovMuHCphd6r:b-r72nq7) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L57)):*
> ```Markdown
> 
>     ```java
>     dependencies {
> ```

version should be 3.1.+ or 3.2.+
___
*[`other/native-with-flutter-components.md` line 316 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NuiSvuT4bH0N3u6zJ41:-NuiSvuT4bH0N3u6zJ42:b-xz4jhi) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L316)):*
> ```Markdown
> 
>     @UIApplicationMain
>     class AppDelegate:  FlutterAppDelegate {
> ```

think you are missing override keywork here

**Comment by MikePendo** [comment]
*[`other/native-with-flutter-components.md` line 202 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-Nusvz78BgVcl3RqR58H:-Nusvz78BgVcl3RqR58I:b-maj73o) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L202)):*
> ```Markdown
> <br>
> 
> Using Swift, to access the PendoSDK.h, include it in the Bridging-Header.h of your app, adding: <br> `#import "PendoSDK.h"`
> ```

@noambartouv can we please verify if we need the Bridging header i.e cant we use just the module? NB

**Comment by MikePendo** [comment]
*[`other/native-with-flutter-components.md` line 253 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-Nusw8-U8P1GM1Iz0mYt:-Nusw8-U8P1GM1Iz0mYu:b6wbmfn) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L253)):*
> ```Markdown
> @import Flutter;
> @import Pendo;
> #import "PendoSDK.h"
> ```

I dont think you need header and the module if its not `.mm` lets use only the module

**Comment by MikePendo** [comment]
*[`other/native-with-flutter-components.md` line 1 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NusvBqn8zt4q7MjWwaQ:-NusvBqn8zt4q7MjWwaR:bpvss4q) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L1)):*
> ```Markdown
> # Native application with Flutter components
> ```

@noambartouv I am confused. 
The easiest flow that we currently can support is Flutter with Native. i.e initiate the SDK in Flutter and call any native api from native. That will cost a zero effort from the client.
Your description here is installing the SDK on Native I think we should go the other way around

**Comment by MikePendo** [comment]
*[`other/native-with-flutter-components.md` line 117 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NusxITG36IG1aCwcLXt:-NusxITG36IG1aCwcLXu:b-aflr8e) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L117)):*
> ```Markdown
>         // connect to Pendo's server
>         Pendo.setup(
>         this,
> ```

what is this?

**Review by randmaayan — COMMENTED** [review]
> Reviewed 17 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: 18 of 19 files reviewed, 8 unresolved discussions (waiting on @MikePendo, @noambartouv, and @udilevin)

___
*[`other/native-with-flutter-components.md` line 12 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-Nut94An7XTcwl83DysR:-Nut94An7XTcwl83DysS:bo58hdc) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L12)):*
> ```Markdown
> 
> >[!NOTE]
> >These instructions assume prior knowledge of Flutter component integration into your native app. If you don't, use this official Flutter documentation to learn how this can be done.
> ```

please rephrase. 
If you don't what? 
Whats the official documentation ?

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: 17 of 21 files reviewed, 8 unresolved discussions (waiting on @MikePendo, @randmaayan, and @udilevin)

___
*[`other/native-with-flutter-components.md` line 1 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NusvBqn8zt4q7MjWwaQ:-NuzRjo8DgCZQDiFDV1j:b-54z0jk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L1)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@noambartouv I am confused. 
The easiest flow that we currently can support is Flutter with Native. i.e initiate the SDK in Flutter and call any native api from native. That will cost a zero effort from the client.
Your description here is installing the SDK on Native I think we should go the other way around
</blockquote></details>

This is an existing [article](https://support.pendo.io/hc/en-us/articles/4402603425549-Install-native-application-with-Flutter-components) that deals with native apps that have started migrating to flutter. It allows codeless from the native side and track events to be sent from the dart side. I was asked to move it from the resource center as technical documentation is now in github.

What you are suggesting would start the session on the flutter side and turn the entire app into track-event-only.  
___
*[`other/native-with-flutter-components.md` line 12 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-Nut94An7XTcwl83DysR:-NuzW5Kt68MRTW-6MXkq:bxs6i3d) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L12)):*
<details><summary><i>Previously, randmaayan wrote…</i></summary><blockquote>

please rephrase. 
If you don't what? 
Whats the official documentation ?
</blockquote></details>

Thanks, check updated push
___
*[`other/native-with-flutter-components.md` line 28 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NuiSRl0C7nUuJWrpPBY:-NuzWKrJDZpW-jaE8Nis:bb7f2mf) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L28)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

should probably be 3.1 or even 3.2
</blockquote></details>

done
___
*[`other/native-with-flutter-components.md` line 57 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NuiSX-HBovMuHCphd6q:-NuzWUwo6uwhKiZoJt8x:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L57)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

version should be 3.1.+ or 3.2.+
</blockquote></details>

Done.
___
*[`other/native-with-flutter-components.md` line 117 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NusxITG36IG1aCwcLXt:-NuzW_52AAxVDW-cOpRZ:b-dlvr1a) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L117)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

what is this?
</blockquote></details>

In Android the customer passes the application. This is normal part of the integration

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: 17 of 21 files reviewed, 8 unresolved discussions (waiting on @MikePendo, @randmaayan, and @udilevin)

___
*[`other/native-with-flutter-components.md` line 117 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NusxITG36IG1aCwcLXt:-Nuzu1J62-oOBvfgVSoM:b-j4t7s8) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L117)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

In Android the customer passes the application. This is normal part of the integration
</blockquote></details>

I'll take a look though if native instructions are a bit more informative and if we can take what we have there

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: 13 of 21 files reviewed, 8 unresolved discussions (waiting on @MikePendo, @randmaayan, and @udilevin)

___
*[`other/native-with-flutter-components.md` line 202 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-Nusvz78BgVcl3RqR58H:-Nv3CO7s4GBKDHNbG7EN:b-8nr7lv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L202)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@noambartouv can we please verify if we need the Bridging header i.e cant we use just the module? NB
</blockquote></details>

Fixed. This was a mistake should have been PendoFlutterPlugin instead of PendoSDK (got confused with the new alias in 3.0)
___
*[`other/native-with-flutter-components.md` line 253 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-Nusw8-U8P1GM1Iz0mYt:-Nv3Ce_B2XzH8fWuD-F3:bs9t98h) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L253)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

I dont think you need header and the module if its not `.mm` lets use only the module
</blockquote></details>

Same fixed to PendoFlutterPlugi.h - let me know if there is still an issue
___
*[`other/native-with-flutter-components.md` line 316 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NuiSvuT4bH0N3u6zJ41:-Nv3CHMt3PWiZZXKrVFn:b-ig6pvd) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L316)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

think you are missing override keywork here
</blockquote></details>

verified - no override keyword needed

**Review by randmaayan — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: all files reviewed, 3 unresolved discussions (waiting on @udilevin)

**Comment by udilevin** [comment]
*[`other/native-with-flutter-components.md` line 316 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NuiSvuT4bH0N3u6zJ41:-Nvbet8PCiftC8fcXRQB:b-prnrxm) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L316)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

verified - no override keyword needed
</blockquote></details>

Please check https://stackoverflow.com/questions/70810646/appdelegate-swift-overriding-declaration-requires-an-override-keyword

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @randmaayan and @udilevin)

___
*[`other/native-with-flutter-components.md` line 316 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133#-NuiSvuT4bH0N3u6zJ41:-Nvbn5jtCBOIx1wxQxf9:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/980f95f0258c4b83081c07bdfe91260fb704e345/other/native-with-flutter-components.md#L316)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Please check https://stackoverflow.com/questions/70810646/appdelegate-swift-overriding-declaration-requires-an-override-keyword
</blockquote></details>

Done.

**Review by udilevin — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Comment by udilevin** [comment]
:lgtm:

**Review by MikePendo — APPROVED** [review]
> Reviewed 12 of 19 files at r1, 3 of 4 files at r2, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Comment by randmaayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-83565](https://pendo-io.atlassian.net/browse/APP-83565): Jira Issue APP-83565: Changed to Resolved


Branch APP-83565-native-with-flutter-components deleted

**Pull request merged**
