### PR TITLE
Adjust a setup and startSession api documentation

### PR DESCRIPTION
**Pull request by DavidPendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/213)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[08d79e7](https://github.com/pendo-io/pendo-mobile-sdk/pull/213/commits/08d79e768ea58b8ac9c0e3a473264f6b9f4ad9aa)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[13c6760](https://github.com/pendo-io/pendo-mobile-sdk/pull/213/commits/13c67606f5420ea52e47b8499120f21baf3676f7)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[f3bbaa3](https://github.com/pendo-io/pendo-mobile-sdk/pull/213/commits/f3bbaa36865f68f1416facdf59c20186a801c7bc)

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/213)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @naorlevi and @noambartouv)

**Comment by udilevin** [comment]
:lgtm:

**Pull request closed without merging**
