### PR TITLE
APP-99673 Update Package.swift

### PR DESCRIPTION
**Pull request by MaximShnirman**
version update

- - -
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/130)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1e874bb](https://github.com/pendo-io/pendo-mobile-sdk/pull/130/commits/1e874bb49d2bcbb36c419d1eeae17a8929278c41)

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/130)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaximShnirman)

**Comment by udilevin** [comment]
:lgtm:

**Comment by udilevin** [comment]
[check]

**Comment by pendo-ops** [comment]
Okay, All checks were run. Did not encounter any errors.

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch MaximShnirman-patch-1 deleted

**Pull request merged**
