### PR TITLE
APP-108450 sendClickAnalytic name fix

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/170)

### CODE REVIEW

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/170#-:-O5TKQAx6Nc5ewyoY-Dt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shlomipendo and @udilevin)

**Review by udilevin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/170)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shlomipendo)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues need reviews:
* [APP-108450](https://pendo-io.atlassian.net/browse/APP-108450): Needs Senior Review

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-108450](https://pendo-io.atlassian.net/browse/APP-108450): Resolved


Branch APP-108450_sendClickAnalytic_doc_fix deleted

**Pull request merged**
