### PR TITLE
APP-99851 Update Package.swift

### PR DESCRIPTION
**Pull request by MaximShnirman**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/131)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[d75201e](https://github.com/pendo-io/pendo-mobile-sdk/pull/131/commits/d75201ebca3dc2037c97fa92a753eb2cde9489e6)

**Review by orendayan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/131)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaximShnirman)

**Review by TehilaTaub — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/131#-:-NuZ9Aps14YFw7P-GgPs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MaximShnirman)

**Comment by orendayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch MaximShnirman-patch-1 deleted

**Pull request merged**
