### PR TITLE
APP-112745 fix modal type to be more accurate

### PR DESCRIPTION
**Pull request by TehilaTaub**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/205)

### CODE REVIEW

**Comment by MikePendo** [comment]
:lgtm:

**Review by randmaayan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/205)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TehilaTaub)

**Comment by randmaayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-112745](https://pendo-io.atlassian.net/browse/APP-112745): Jira Issue APP-112745: Changed to Resolved


Branch APP-112745_change_supported_type_in_withPendoModal_API deleted

**Pull request merged**
