### PR TITLE
Add license file

### PR DESCRIPTION
**Pull request by udilevin**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/97)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[a4d3d00](https://github.com/pendo-io/pendo-mobile-sdk/pull/97/commits/a4d3d00a0580e446bef2c57777ab6a801089525d)

**Review by DavidFaermanPendo — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/97)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Review by DavidFaermanPendo — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/97#-:-NlXokGA8_KE07hWcQZj:b3sq3yz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-93962](https://pendo-io.atlassian.net/browse/APP-93962): Invalid state 'Triage' for merge into master

**Comment by DavidFaermanPendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issue transitions/labels succeeded, but some didn't.
Total number of issues: 1
Issues that successfully transitioned/labeled: 1
Issues that weren't transitioned/labeled: 1
Problems encountered:
* [APP-93962](https://pendo-io.atlassian.net/browse/APP-93962): Jira Issue APP-93962: Not changed to Resolved - Status code from JIRA was not successful. 400


Branch APP-93962 deleted

**Comment by JetFault** [comment]
The license takes you to a 404 page

**Pull request merged**
