### PR TITLE
APP-86708 proguard rules updated, parametrizedType

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/69)

### CODE REVIEW

**Review by rotemelem6 — APPROVED** [review]

**Review by DavidFaermanPendo — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Review by DavidFaermanPendo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/69#-:-NcHBTXx2TGQtQEPy6wy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Review by DavidFaermanPendo — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/69#-:-NcHBV7C4zvY2JTMdruM:b3sq3yz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-86708](https://pendo-io.atlassian.net/browse/APP-86708): Resolved


Branch APP-86708_moshi_gradle_8_parametrizedType deleted

**Pull request merged**
