### PR TITLE
App 81788 update

### PR DESCRIPTION
**Pull request by udilevin**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/42)

### CODE REVIEW

**Review by MikePendo — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/42#-:-NVddz-yDZOt0GMSJo7N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Comment by MikePendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-81778](https://pendo-io.atlassian.net/browse/APP-81778): Invalid state 'Backlog' for merge into master

**Review by cohenam — COMMENTED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/42#-:-NVdfuZB0-4vB_GuvLsH:b3sq3yz)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @udilevin)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-81788](https://pendo-io.atlassian.net/browse/APP-81788): Resolved


Branch APP-81778-Update deleted

**Pull request merged**
