### PR TITLE
APP-95046 3.1 updates

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/112)

### CODE REVIEW

**Review by DavidPendo — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/112)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Review by TehilaTaub — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/112#-:-Npxb5dA8vPzOSkyoMZp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Review by TehilaTaub — COMMENTED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/112#-:-Npxhns27X4MFhwYngXH:b3sq3yz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-95046](https://pendo-io.atlassian.net/browse/APP-95046): Resolved


Branch APP-95046_3.1 deleted

**Pull request merged**
