### PR TITLE
APP-94641 Updated all frameworks pauseGuides API documentation

### PR DESCRIPTION
**Pull request by TehilaTaub**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/106)

### CODE REVIEW

**Review by TehilaTaub — COMMENTED** [review]
It is aligned with Android - https://pendo-io.atlassian.net/browse/APP-94641.
It was approved by @juliebenjamin.

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/106#-:-Novn2BJ5day6gWPs5G4:bh5zxa)* status: 0 of 6 files reviewed, all discussions resolved

**Review by TehilaTaub — COMMENTED** [review]
Android ticket - https://pendo-io.atlassian.net/browse/APP-94254

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/106#-:-NovnaXl6sx2XF-dD59J:b5zwlpy)* status: 0 of 6 files reviewed, all discussions resolved

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/106#-:-NovvlpV7RIDLrtwf2J7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TehilaTaub)

**Review by randmaayan — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TehilaTaub)

**Comment by MikePendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues need reviews:
* [APP-94641](https://pendo-io.atlassian.net/browse/APP-94641): Unknown value for the Data Privacy Review field.

**Comment by randmaayan** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-94641](https://pendo-io.atlassian.net/browse/APP-94641): Jira Issue APP-94641: Changed to Resolved


Branch APP_94641_Update_all_frameworks_pauseGuides_and_resumeGuides_API_documentation deleted

**Pull request merged**
