### PR TITLE
APP-91996 SDK 3.0 docs feature branch

### PR DESCRIPTION
**Pull request by noambartouv**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/84)

### CODE REVIEW

**Review by randmaayan — APPROVED** [review]
:lgtm: 

> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/84#-:-NkPTtf90b7h5IZOj198:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Review by MikePendo — APPROVED** [review]
> Reviewed 36 of 40 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/84)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Comment by MikePendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-88575](https://pendo-io.atlassian.net/browse/APP-88575): Resolved
* [APP-88967](https://pendo-io.atlassian.net/browse/APP-88967): Resolved
* [APP-91687](https://pendo-io.atlassian.net/browse/APP-91687): Resolved
* [APP-91991](https://pendo-io.atlassian.net/browse/APP-91991): Resolved


Branch APP-91996-SDK.3.0-DOCS-feature-branch deleted

**Pull request merged**
