### PR TITLE
APP-88575 migration docs

### PR DESCRIPTION
**Pull request by noambartouv**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77)

### CODE REVIEW

**Comment by MikePendo** [comment]
*[`migration-docs/ios-2.x-to-3.x-migration.md` line 153 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-Nih-SCd3vvNU_s0DopH:-Nih-SCd3vvNU_s0DopI:b-fwsxlx) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83c5b305fb45d45541728d06af2afd634c6e002c/migration-docs/ios-2.x-to-3.x-migration.md#L153)):*
> ```Markdown
> 
> ```swift
> PendoManager.shared().setup("someAppKey", with: nil)
> ```

Do we need `with:`?

**Comment by MikePendo** [comment]
*[`migration-docs/README.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-Nih07G522EzvJMT8hhg:-Nih07G522EzvJMT8hhh:b9ipds3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83c5b305fb45d45541728d06af2afd634c6e002c/migration-docs/README.md#L7)):*
> ```Markdown
> - [Native Android](/migration-docs/android-2.x-to-3.x-migration.md)
> - [Native iOS](/migration-docs/ios-2.x-to-3.x-migration.md)
> - [React Native](/migration-docs/react-native-2.x-to-3.x-migration.md)
> ```

maybe lets add `/react native navigation` near `React Native`

**Review by MikePendo — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77)* status: all files reviewed, 2 unresolved discussions (waiting on @noambartouv)

**Review by randmaayan — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77)* status: all files reviewed, 6 unresolved discussions (waiting on @noambartouv)

___
*[`migration-docs/android-2.x-to-3.x-migration.md` line 5 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-NihuqjO-CvgG9buFYjU:-NihuqjO-CvgG9buFYjV:bo20nwb) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83c5b305fb45d45541728d06af2afd634c6e002c/migration-docs/android-2.x-to-3.x-migration.md#L5)):*
> ```Markdown
> ## Changes Relevant to All Native Android Apps
> 
> The following deprecated APIs have benn removed. Follow these instructions to replace them: 
> ```

been (its in all files)
___
*[`migration-docs/android-2.x-to-3.x-migration.md` line 175 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-NihwDZaD-SBvp1nF0dB:-NihwDZaD-SBvp1nF0dC:b-8izggr) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83c5b305fb45d45541728d06af2afd634c6e002c/migration-docs/android-2.x-to-3.x-migration.md#L175)):*
> ```Markdown
> <td>
> 
> Call `Pendo.startSession`` with the new account id value instead of `Pendo.setAccountId`:
> ```

you have an extra ` after startSession.
___
*[`migration-docs/README.md` line 12 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-NihuRsOAmnwXjItEzhI:-NihuRsOAmnwXjItEzhJ:b-xp8id7) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83c5b305fb45d45541728d06af2afd634c6e002c/migration-docs/README.md#L12)):*
> ```Markdown
> - [Flutter](/migration-docs/flutter-2.x-to-3.x-migration.md)
> 
> Xamarin iOS and Xamarin Android are no longer supurted in 3.x. Please move to MAUI or Xamarin Forms SDKs. This requires creating a new Pendo App and recapturing the app pages and features.
> ```

supported.
___
*[`migration-docs/react-native-2.x-to-3.x-migration.md` line 4 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-NihubTK2MHt06IhPSdv:-NihubTK2MHt06IhPSdw:bb7dl0x) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83c5b305fb45d45541728d06af2afd634c6e002c/migration-docs/react-native-2.x-to-3.x-migration.md#L4)):*
> ```Markdown
> 
> 
> The following deprecated APIs have benn removed. Follow these instructions to replace them:
> ```

been

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @MikePendo)

___
*[`migration-docs/ios-2.x-to-3.x-migration.md` line 153 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-Nih-SCd3vvNU_s0DopH:-Niktt9Q7MslnqOQn9dU:b-o4ughs) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83c5b305fb45d45541728d06af2afd634c6e002c/migration-docs/ios-2.x-to-3.x-migration.md#L153)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

Do we need `with:`?
</blockquote></details>

I kept it there in case they were using PendoOptions (in initSDKWithoutVisitor it was required - we didn't create an overload without pendoOptions)

**Review by TehilaTaub — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-:-NimnAAs3kn7NIkdhUOn:bnfp4nl)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @MikePendo and @noambartouv)

**Review by randmaayan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @MikePendo and @noambartouv)

___
*[`migration-docs/android-2.x-to-3.x-migration.md` line 23 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-Nimv0iU426o9h8saHVI:-Nimv0iU426o9h8saHVJ:bia8twv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/54f2156f1d56e23b3fe9f3bc4d0677aa809cf821/migration-docs/android-2.x-to-3.x-migration.md#L23)):*
> ```Markdown
> 
> ```kotlin
> // set session paramaters
> ```

*parameters

**Comment by MikePendo** [comment]
:lgtm:

**Review by MikePendo — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77)* status: all files reviewed, 2 unresolved discussions (waiting on @noambartouv)

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @MikePendo and @randmaayan)

___
*[`migration-docs/README.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-Nih07G522EzvJMT8hhg:-Nipb3771Dp4MPYAUY89:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83c5b305fb45d45541728d06af2afd634c6e002c/migration-docs/README.md#L7)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

maybe lets add `/react native navigation` near `React Native`
</blockquote></details>

Done.

**Comment by udilevin** [comment]
*[`migration-docs/maui-2.x-to-3.x-migration.md` line 28 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-NipfWUY0KCIZyYrDoI6:-NipfWUY0KCIZyYrDoI7:buzhe6h) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/393977f46c56e67b7c71a98ed0453402aa036c88/migration-docs/maui-2.x-to-3.x-migration.md#L28)):*
> ```Markdown
> <b>3.x:</b>
> 
> ```C#
> ```

Lower case Pendo
Check if(pendo !=null)

**Comment by udilevin** [comment]
*[`migration-docs/react-native-2.x-to-3.x-migration.md` line 18 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77#-NipfoLC8IdCg28bxYy0:-NipfoLC8IdCg28bxYy1:bz169hm) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/393977f46c56e67b7c71a98ed0453402aa036c88/migration-docs/react-native-2.x-to-3.x-migration.md#L18)):*
> ```Markdown
> <td align=center><b>withPendoRN </td>
> <td>
> ```

Capital W in WithPendoReactNavigation

**Comment by MikePendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issue transitions/labels succeeded, but some didn't.
Total number of issues: 1
Issues that successfully transitioned/labeled: 0
Issues that weren't transitioned/labeled: 0
Problems encountered:


Branch APP-88575-migration-docs deleted

**Pull request merged**
