### PR TITLE
APP-94830 pendo effects in maui (3.1)

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108)

### CODE REVIEW

**Review by TehilaTaub — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108#-:-NpKaS888aocLnJfFfqA:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @randmaayan)

___
*[`android/pnddocs/xamarin_maui-android.md` line 115 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108#-NpKv7kX22U373tXbxYP:-NpKv7kX22U373tXbxYQ:bel9yee) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/4d2385cc9b42f770be98067919dff452aed9710d/android/pnddocs/xamarin_maui-android.md#L115)):*
> ```Markdown
> 
> 
> 3. If your app is using Gestures, register **Pendo Effects** (PendoRoutingEffect, PendoPlatformEffect) in your **MauiProgram.cs** file as shown in the code below. This is relevant for SDK version 3.1 and above.
> ```

Something about the "If using gestures" and "relevant from SDK 3.1" isn't right in my opinion. Should somehow be combined. 

Maybe open with: (Available/Required from SDK 3.1) If using ...

**Review by noambartouv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @randmaayan)

___
*[`android/pnddocs/xamarin_maui-android.md` line 115 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108#-NpKw8Li6uivu-64YgOx:-NpKw8Li6uivu-64YgOy:bc0zc4q) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/4d2385cc9b42f770be98067919dff452aed9710d/android/pnddocs/xamarin_maui-android.md#L115)):*
> ```Markdown
> 
> 
> 3. If your app is using Gestures, register **Pendo Effects** (PendoRoutingEffect, PendoPlatformEffect) in your **MauiProgram.cs** file as shown in the code below. This is relevant for SDK version 3.1 and above.
> ```

This should be considered in the migration docs from 2.x to 3.x as well

**Review by randmaayan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @noambartouv)

___
*[`android/pnddocs/xamarin_maui-android.md` line 115 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108#-NpKw8Li6uivu-64YgOx:-NpOFFHz1i2d44ol2mcA:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/4d2385cc9b42f770be98067919dff452aed9710d/android/pnddocs/xamarin_maui-android.md#L115)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

This should be considered in the migration docs from 2.x to 3.x as well
</blockquote></details>

Done.

**Comment by DavidPendo** [comment]
*[`android/pnddocs/xamarin_maui-android.md` line 115 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108#-NpPUGlr1c8F0cvp3qHF:-NpPUGlr1c8F0cvp3qHG:bmf8fqo) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f04457f6b144d850e60f5fcba6bead171a87c646/android/pnddocs/xamarin_maui-android.md#L115)):*
> ```Markdown
> 
> 
> 3. If your app is using **Gestures**, you must upgrade to SDK version 3.1 or above and then register **Pendo Effects** (PendoRoutingEffect, PendoPlatformEffect) in your **MauiProgram.cs** file as shown in the code below. 
> ```

*you must upgrade* maybe it should come with a more gentle pronunciation... 

... to support ...bla bla... you **need** to upgrade to

**Comment by DavidPendo** [comment]
*[`android/pnddocs/xamarin_maui-android.md` line 115 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108#-NpPUGlr1c8F0cvp3qHF:-NpPVEBHEZzf0Ys1EQYV:b320eid) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f04457f6b144d850e60f5fcba6bead171a87c646/android/pnddocs/xamarin_maui-android.md#L115)):*
<details><summary><i>Previously, DavidPendo wrote…</i></summary><blockquote>

*you must upgrade* maybe it should come with a more gentle pronunciation... 

... to support ...bla bla... you **need** to upgrade to
</blockquote></details>

If your app is using **Gestures**, **to support detecting click analytics you need** upgrade to SDK version 3.1 or above and then register **Pendo Effects** (PendoRoutingEffect, PendoPlatformEffect) in your **MauiProgram.cs** file as shown in the code below.

**Review by DavidPendo — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108)* status: all files reviewed, 1 unresolved discussion (waiting on @noambartouv)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108#-:-NpQ-IYh2hdHOIfrjmkK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Review by TehilaTaub — COMMENTED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108#-:-NpthJK4-sn4kYn26Q9q:b3sq3yz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-94830](https://pendo-io.atlassian.net/browse/APP-94830): Jira Issue APP-94830: Changed to Resolved


Branch APP-94830_maui_effect_31 deleted

**Pull request merged**
