### PR TITLE
APP-89204 v13 for android

### PR DESCRIPTION
**Pull request by randmaayan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/78)

### CODE REVIEW

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/78#-:-Nj7etHw2Qu6lkB_3-8Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randmaayan)

**Comment by noambartouv** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issue transitions/labels succeeded, but some didn't.
Total number of issues: 1
Issues that successfully transitioned/labeled: 1
Issues that weren't transitioned/labeled: 1
Problems encountered:
* [APP-89204](https://pendo-io.atlassian.net/browse/APP-89204): Jira Issue APP-89204: Not changed to Resolved - Status code from JIRA was not successful. 400


Branch APP-89204_v13_android deleted

**Pull request merged**
