### PR TITLE
APP-98154 add ScreenContentChanged API

### PR DESCRIPTION
**Pull request by udilevin**
fix styling

- - -
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[05cafe3](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/05cafe3918b1c2a10a1307dfacd3d0ffe1ecbcaf)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[05cafe3](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/05cafe3918b1c2a10a1307dfacd3d0ffe1ecbcaf)
[c2108aa](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/c2108aa879e53856b9b73b5fae6b10f2dc798c1c)

**Review by randmaayan — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noambartouv)

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)* status: all files reviewed, 5 unresolved discussions (waiting on @udilevin)

___
*[`api-documentation/xamarin-forms-apis.md` line 9 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NshSCx82SKWYh_fq7pj:-NshSCx82SKWYh_fq7pk:b5bwfgk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c2108aa879e53856b9b73b5fae6b10f2dc798c1c/api-documentation/xamarin-forms-apis.md#L9)):*
> ```Markdown
> 
> ### IPendoInterface APIs
> [PendoInterface](#ipendointerface) ⇒ `IPendoInterface` <br>
> ```

I think let's change the visual text to IPendoInterface as well
___
*[`api-documentation/xamarin-forms-apis.md` line 48 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NshURHp6xzWMXVwateV:-NshURHp6xzWMXVwateW:b92vqt3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c2108aa879e53856b9b73b5fae6b10f2dc798c1c/api-documentation/xamarin-forms-apis.md#L48)):*
> ```Markdown
>     public partial class App : Application
>     {
>         private static IPendoInterface pendo = DependencyService.Get<IPendoInterface>();
> ```

"pendo" does not match the examples which are all "Pendo". Do we need to change them? (both from & MAUI)
___
*[`api-documentation/xamarin-forms-apis.md` line 289 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NshSu-iEav9FtWuh-yo:-NshSu-iEav9FtWuh-yp:b-47iqpi) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c2108aa879e53856b9b73b5fae6b10f2dc798c1c/api-documentation/xamarin-forms-apis.md#L289)):*
> ```Markdown
> <b>Class:</b> PendoInterface
> <br><b>Kind:</b> class method<br>
> <br><b>Returns:</b> void
> ```

why the additional extra line break? Different than the other API details 
___
*[`api-documentation/xamarin-maui-apis.md` line 9 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NshU0GQ6icViROOZuZH:-NshU0GQ6icViROOZuZI:b-j2txnt) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c2108aa879e53856b9b73b5fae6b10f2dc798c1c/api-documentation/xamarin-maui-apis.md#L9)):*
> ```Markdown
> 
> ### IPendoInterface APIs
> [PendoInterface](#ipendoservice) ⇒ `IPendoService` <br>
> ```

Same? (visual text as well?)
___
*[`api-documentation/xamarin-maui-apis.md` line 48 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NshVW266Z6i9kGBIdVO:-NshVW266Z6i9kGBIdVP:b-jq3can) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c2108aa879e53856b9b73b5fae6b10f2dc798c1c/api-documentation/xamarin-maui-apis.md#L48)):*
> ```Markdown
>     public partial class App : Application
>     {
>         IPendoService pendo = PendoServiceFactory.CreatePendoService();
> ```

same here with "pendo" vs other examples using "Pendo"

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[05cafe3](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/05cafe3918b1c2a10a1307dfacd3d0ffe1ecbcaf)
[c2108aa](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/c2108aa879e53856b9b73b5fae6b10f2dc798c1c)
[3b09b79](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/3b09b79c4fd0d0be140fc35c448fcc1f37c64dd7)

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @randmaayan and @udilevin)

___
*[`api-documentation/xamarin-forms-apis.md` line 289 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-Nsi6Abh-WLKPbvu_Izv:-Nsi6t0R3YeiCY4026Cv:bp4pfww) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/3b09b79c4fd0d0be140fc35c448fcc1f37c64dd7/api-documentation/xamarin-forms-apis.md#L289)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

unneccessary <br> *
</blockquote></details>

uneccessary br *

**Review by noambartouv — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Review by noambartouv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)* status: all files reviewed, 2 unresolved discussions (waiting on @udilevin)

___
*[`api-documentation/xamarin-forms-apis.md` line 454 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NvYAFgk11tHEGSoeJ6n:-NvYAFgk11tHEGSoeJ6o:b-jjy1mv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83a1e1a61317b54b5854527f2101e0e6ac7b6de4/api-documentation/xamarin-forms-apis.md#L454)):*
> ```Markdown
> >Rescans the page enabling the Pendo SDK to identify changes that have occurred since the page loaded.
> 
> >Using this API is required to display tooltip guides on elements that weren't present, or have been modified since the initial page load.
> ```

It also fixes RAClicks on Android (adds PendoDelgate to the new elements).

Suggested new copy:

Using this API is required to display tooltip guides and fix inaccurate analytics on elements that weren't present, or have been modified since the initial page load.
___
*[`api-documentation/xamarin-maui-apis.md` line 470 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NvYAv8V9yBmZHkeo6nB:-NvYAv8V9yBmZHkeo6nC:bb7od0r) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83a1e1a61317b54b5854527f2101e0e6ac7b6de4/api-documentation/xamarin-maui-apis.md#L470)):*
> ```Markdown
> >Rescans the page enabling the Pendo SDK to identify changes that have occurred since the page loaded.
> 
> >Using this API is required to display tooltip guides on elements that weren't present, or have been modified since the initial page load.
> ```

same

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[83a1e1a](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/83a1e1a61317b54b5854527f2101e0e6ac7b6de4)
[a137fc4](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/a137fc46d43053943cb144b1512bd7331880f10d)

**Review by udilevin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)* status: all files reviewed, 2 unresolved discussions (waiting on @noambartouv)

___
*[`api-documentation/xamarin-forms-apis.md` line 454 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NvYAFgk11tHEGSoeJ6n:-Nvbbk3yEjAzgJZZDzcv:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83a1e1a61317b54b5854527f2101e0e6ac7b6de4/api-documentation/xamarin-forms-apis.md#L454)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

It also fixes RAClicks on Android (adds PendoDelgate to the new elements).

Suggested new copy:

Using this API is required to display tooltip guides and fix inaccurate analytics on elements that weren't present, or have been modified since the initial page load.
</blockquote></details>

Done.
___
*[`api-documentation/xamarin-maui-apis.md` line 470 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119#-NvYAv8V9yBmZHkeo6nB:-NvbbjqSBWrVbuipCzP0:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/83a1e1a61317b54b5854527f2101e0e6ac7b6de4/api-documentation/xamarin-maui-apis.md#L470)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[e27624c](https://github.com/pendo-io/pendo-mobile-sdk/pull/119/commits/e27624c6bfb052b75b2f6792d1d384975c2f378e)

**Comment by udilevin** [comment]
[check]

**Comment by pendo-ops** [comment]
Okay, All checks were run. Did not encounter any errors.

**Review by noambartouv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Comment by MaximShnirman** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-98154](https://pendo-io.atlassian.net/browse/APP-98154): Jira Issue APP-98154: Changed to Resolved


Branch APP-98154 deleted

**Pull request merged**
